### ISSUE TITLE
Enhancement in graphics.py to change odds text size

### ISSUE THREAD

**Issue by MaximilianoMoll** [pzivich/zEpid#161]
Please consider to change the followings in graphics.py in order to improve text resizing in forest plot:
-line 127:
 def plot(self, figsize=(3, 3), t_adjuster=0.01, decimal=3, size=3, max_value=None, min_value=None):
with
 def plot(self, figsize=(3, 3), t_adjuster=0.01, decimal=3, size=3, max_value=None, min_value=None, odds_text_size=12):

-line 216:
tb.set_fontsize(12)
with
tb.set_fontsize(odds_text_size)

**Comment by pzivich** [comment]
Thank you for the suggestion. I will work on adding
