### ISSUE TITLE
sklearn dependancy in setup.py should be scikit-learn

### ISSUE THREAD

**Issue by gsbowlin** [pzivich/zEpid#165]
When installing locally, it looks like the setup.py is incorrectly listing dependencies resulting in the following pip list

scikit-learn              0.24.20 <-- Already installed before installing zEpid
sklearn                   0.0 <-- added after installing zEpid, but not really sklearn. 

The first is the correct package, but the second is very out of date. 

See the pypi reference for sklearn: https://pypi.org/project/sklearn/

**Comment by pzivich** [comment]
thanks! that is my mistake. Will fix
