### ISSUE TITLE
conf.py missing?

### ISSUE THREAD

**Issue by CamDavidsonPilon** [pzivich/zEpid#41]
Working on lifelines docs, I was editing my `conf.py` file - which is a config file for Sphinx and Readthedocs. I don't see a conf.py in zepid, which makes me wonder how zepid.readthedocs.io is even working...

**Comment by pzivich** [comment]
Hmmm that's a good question... there isn't a ``conf.py`` file

**Comment by pzivich** [comment]
Working ``conf.py`` file is now added to the docs and part of the master branch
