### ISSUE TITLE
Suggestion: used NamedTuples in calc utils

### ISSUE THREAD

**Issue by CamDavidsonPilon** [pzivich/zEpid#42]
This became clear in reading the tests like:
```python
    def test_match_sas_ci(self):
        sas_ci = (0.361409618, 0.638590382)
        r = risk_ci(25, 50, confint='wald')
        npt.assert_allclose(r[1:3], sas_ci)
```

It's not clear what `r[1:3]` represents, or `r[0]`, etc.

My suggestion is to create a [`NamedTuple`](https://docs.python.org/3/library/typing.html#typing.NamedTuple) at the top of the file:
```python
from typing import NamedTuple
...

class CalcResults(NamedTuple):
    name: string
    point_estimate: float
    lower_bound: float
    upper_bound: float
    standard_error: float

def incidence_rate_ci(events, time, alpha=0.05):
   ...

    return CalcResults('incidence_date', ir, lower, upper, sd)
```

and then users (and yourself) can access elements easier:

```
result = incidence_rate_ci(...)
result.point_estimate
result.standard_error
```

A `NamedTuple` is like a light-weight class - another option is lean in and create a full-on class with methods, etc.

**Comment by CamDavidsonPilon** [comment]
I'd be happy to own implementing this - okay with you?

**Comment by pzivich** [comment]
Works for me. Thanks!
