### ISSUE TITLE
Travis CI and matplotlib

### ISSUE THREAD

**Issue by pzivich** [pzivich/zEpid#44]
I got Travis CI to check that all plots return axes objects once. Now it's having some trouble...

Everything passes locally and Travis is using the same version of matplotlib that I am using locally. Maybe something with the OS?...

**Comment by pzivich** [comment]
https://github.com/pymc-devs/pymc3/issues/474

**Comment by CamDavidsonPilon** [comment]
hm, 

1) do we need to run matplotlib tests on travis? In my libs, I isolate the plotting tests and will run them locally to make sure things look okay visually. Not a great nor robust test, but sufficient I suppose. 

2) It's asking for a `$DISPLAY` variable. What about faking this and adding this line to the travis.yml:
```
script:
   DISPLAY=1 pytest
```
I have no idea if that will work - I imagine a new error will come up.

**Comment by pzivich** [comment]
Honestly, I am not sure how important the matplotlib tests I have are. All they really assess is that an axes object is returned. They would catch some error within the plot, but not that the plot is displaying correctly. I have another script (not in tests) that prints out all the plots for me to manually check. 

I will pull out all the tests for plots from tests that go to travis and keep them aside for manual checks

**Comment by pzivich** [comment]
No matplotlib checks are in tests/*

Instead there is tests/test_graphics_manual.py, which can be run to check all the graphs manually. This is better, since my checks did not compare the plots
